name: Upload Build Scans

on:
  workflow_run:
    workflows: [ "Verify Build" ]
    types: [ completed ]

jobs:

  publish-build-scans:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      pull-requests: write
    steps:
      - name: Setup Build Scan link capture
        uses: gradle/develocity-actions/maven-setup@d210e6198400f065441127a96568744492dc9bbc
      - name: Publish Build Scans
        uses: gradle/develocity-actions/maven-publish-build-scan@d210e6198400f065441127a96568744492dc9bbc
        with:
          develocity-url: 'https://scans.gradle.com'
