name: Verify Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Setup Maven
        uses: gradle/develocity-actions/maven-setup@welandaz/detect-extension-enforce-custom-coord
        with:
          develocity-url: 'https://scans.gradle.com'
          develocity-injection-enabled: 'true'
          develocity-maven-extension-version: '1.21.6'
          develocity-allow-untrusted-server: 'true'
          develocity-capture-file-fingerprints: 'false'
          develocity-enforce-url: 'true'
      - name: Build with Maven
        run: mvn clean package
